# Site Settings
title: Patrick Morgan
email: pamorgan12@gmail.com
description: "Patrick Morgan Portfolio"
baseurl: ""
url: "http://patrickmorgan.me"

# Build Settings
source: src
destination: _site
markdown: redcarpet
highlighter: rouge
sass:
  style: expanded
