# Site Settings
title: Patrick Morgan
email: pamorgan12@gmail.com
description: "Personal site for Patrick Morgan"
baseurl: ""
url: "http:patrickmorgan.me"

# Build Settings
markdown: redcarpet
highlighter: pygments
sass:
  style: compressed
